### PR TITLE
Add Address/Memory Sanitizer and Valgrind builds

### PR DESCRIPTION
**Pull request by nightlark**
* Adds address sanitizer build (with leak sanitizer disabled, always gives a fatal error)
* Adds memory sanitizer build
* Adds the 179 bus dynamic test case as a test to run for all builds
* Adds a valgrind label to ctest builds (only the 179bus test is tagged with the label right now, execution time goes from 4 seconds without valgrind to 100+ seconds with valgrind)
* Moves code for running tests from Travis config file to bash script for more control over any restrictions on what tests can run together
* Switches daily builds to clang-4.0 from clang-5.0 (interferes with the default version of clang that is installed on Travis, default install has a sanitizer that fails linking step)
* Adds cmake initial cache scripts for sanitizers (setting a variable to a value with spaces causes many problems with parsing the command line -- maybe related to some of the things Travis does when running commands in the yaml file)

### CODE REVIEW

**Comment by nightlark** [comment]
Cron build: https://travis-ci.org/LLNL/GridDyn/builds/395100789

**Review by phlptp — APPROVED** [review]
If we needed to add flags to valgrind, or for one of the sanitizers how easy is that

**Comment by nightlark** [comment]
Adding flags in valgrind should just involve setting CTEST_MEMORYCHECK_COMMAND_OPTIONS in CMakeLists.txt (setting the value with -D didn't seem to work); or not using ctest for running valgrind, though then the path to griddynMain is then hardcoded. The script that runs tests will recognize a --cachegrind option that runs valgrind's cachegrind tool (only the summary is shown, the output file is 50k lines).

Adding flags for the sanitizers would involve opening the asan-cache.cmake or msan-cache.cmake files and adding the flags to the set commands in those scripts (things to try: setting -DCMAKE_CXX_FLAGS and combining the user supplied flags with the initial cmake cache scripts, and using multiple -C options for several cmake cache scripts).

**Comment by nightlark** [comment]
For sanitizer/initial cmake cache files, the priority for who determines the value of a variable that gets set is:
1. -D argument setting a variable
2. An already cached variable value
3. If multiple -C options are given, the first one processed that sets a variable is the one that determines the value

Combining a user-supplied set of flags (in CMAKE_CXX_FLAGS) is not possible, unless the variable with a value set by the user is in a different variable (ex: CMAKE_EXTRA_CXX_FLAGS could be used to then set CMAKE_CXX_FLAGS).

**Pull request merged**
