### PR TITLE
Autobuild update

### PR DESCRIPTION
**Pull request by phlptp**
I updated the autobuild scripts to just use the cmake_build_type on non-windows platforms.  @nightlark  can you take a look, I am not sure how this is going to interact with the cron jobs yet.  But let me know if you see any potential issues or things I missed.

### CODE REVIEW

**Comment by nightlark** [comment]
I think the cron jobs will work with these changes, with the one change being that they will be Release builds. Two questions I had were what happens if a library also has a call to find_package for Boost with a different set of required libraries than those that were already found, and if there is anything to help Sundials find the debug build of SuiteSparse with the "d" postfix?

**Comment by phlptp** [comment]
For the most part I would think we want them to be release builds, sometimes with the debug flags enabled.    As for sundials,  it uses a compile test to make sure the headers are there and it links properly.  That means that it should be ok on linux to directly specify the library.  On Windows I think we need the release build otherwise the linked system libraries have a mismatch.  

For the sundials build there is a dedicated function for systems that are not MSVC and not Mingw.  so we can tweak that if we need to.

**Comment by phlptp** [comment]
Not sure about boost,  the header libraries are all there, but if there was another library that required something I am not sure what it would do.    I think it is additive but I am not sure.  I don't know if addBoost will work that way, but it does build on findBoost, so anyone else using that should be fine.

**Review by nightlark — COMMENTED** [review]
Okay. I don't think the Boost issue will come up for a while, until someone tries to get it building with fskit.

**Comment by phlptp** [comment]
Are we not able to build with FSKIT right now?

**Comment by nightlark** [comment]
FSKIT needs Boost serialization and mpi; it should just be adding a second call to find_boost with those two libraries as required to the CMake file for fskit.

**Comment by phlptp** [comment]
@nightlark  I added some boost stuff to the FSKIT cmakeLists.txt.  I am not sure how to check if that is working or not.  Can you take a look?

**Comment by nightlark** [comment]
The Boost additions to FSKIT work.

**Review by nightlark — APPROVED** [review]

**Pull request merged**
