### PR TITLE
Specify generator for cpack in appveyor's config

### PR DESCRIPTION
**Pull request by mcneish1**
~https://ci.appveyor.com/project/GridDyn/griddyn/build/0.9.1.314~
https://ci.appveyor.com/project/GridDyn/griddyn/build/0.9.1.315

### CODE REVIEW

**Comment by mcneish1** [comment]
I'm not sure why it needs all these extra parameters it didn't need before.

I'd like appveyor to be available because of the ` = default;` and the `&&/||` vs `and/or` things recently. It looks like the build is working, do we need to test the installer here?

I'm leaning towards just taking out the after_build entirely for now

**Comment by phlptp** [comment]
[this](https://github.com/GMLC-TDC/HELICS-src/blob/develop/appveyor.yml) is what we do in HELICS,  I would imagine something similar should work

**Comment by phlptp** [comment]
looks like we would need to -DENABLE_PACKAGE_BUILD=ON  to enable the cpack stuff otherwise it will have no idea what to do

**Comment by mcneish1** [comment]
Confusingly, that's exactly what I started with.

[This](https://github.com/LLNL/GridDyn/commit/81d23c6e17d1301ae55038bb10e65ba33161f0aa) is the diff that broke appveyor in the first place but nothing stands out

**Comment by nightlark** [comment]
@mcneish1 I couldn't commit to the branch in your fork, e6ad673753b7a2bf895a449e7523ce11d0ba5d05 has the change needed to make cpack work

**Pull request closed without merging**
