### PR TITLE
Fix code coverage testing

### LINKED ISSUE #45: issue with code coverage build
There appears to be some issue with the code coverage build on travis after the last merge.

### PR DESCRIPTION
**Pull request by mcneish1**
Fix #45 

I'm not sure how to trigger the code coverage test, I don't think it normally happens for pull requests

### CODE REVIEW

**Comment by phlptp** [comment]
that seems to have broken the builds, @nightlark  would know how to trigger a coverage build

**Comment by phlptp** [comment]
@nightlark  will have to answer that question

**Comment by phlptp** [comment]
I would like @nightlark  to take a look at it and make sure, but I will probably merge this before tonight to see if the coverage runs properly overnight.

**Comment by nightlark** [comment]
The easy way to trigger all of the cron builds like coverage for a branch with changes is to add a new cron job for the branch with the changes on https://travis-ci.org/LLNL/GridDyn/settings -- it takes a minute or so to trigger the build, after which the cron job can be removed. The other way is triggering a build on the Travis dashboard and giving it a modified version of the travis yaml file with the condition for the coverage build changed.

**Comment by mcneish1** [comment]
https://travis-ci.org/LLNL/GridDyn/jobs/458143922 is failing because https://codecov.io/bash is down. The coveralls submission worked.

I'm going to fix lcov-helper.sh to check if the codecov download succeeded, then this should be good to go.

**Comment by phlptp** [comment]
let me know when you are happy with it.

**Comment by mcneish1** [comment]
Should be good to go

**Review by phlptp — APPROVED** [review]

**Pull request merged**
